#!/bin/bash

set -x

yay --answerclean All --answerdiff None --answeredit None --save

yay --noconfirm --needed -Sy \
  alacritty \
  neovim \
  neovim-plug \
  tmux \
  zsh \
  rust \
  npm

sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"


