#!/bin/bash

set -x

# TODO: Make this configurable
# Git configuration
git config --global user.name "Zexa"
git config --global user.email "zexa@cock.li"
git config --global core.excludesfile ~/.gitignore

# Install npm -g packages to home folder
npm config set prefix ~/.npm
