#!/bin/bash
set -x
cd ../dots || exit
find . -type d -exec sh -xvc 'mkdir -p $HOME/${0#"./"}' {} \;
find . -type f -exec sh -xvc 'ln -srf $0 $HOME/${0#"./"}' {} \;

sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
# https://github.com/zsh-users/zsh-autosuggestions/blob/master/INSTALL.md

cargo install 
