#!/bin/bash
set -x
cd .../dots || exit
find . -type d -exec sh -xvc 'mkdir -p $HOME/${0#"./"}' {} \;
find . -type f -exec sh -xvc 'ln -srf $0 $HOME/${0#"./"}' {} \;

sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

