#!/bin/bash
set -x

DISTRIB_ID=$(cat /etc/*-release | grep DISTRIB_ID)
VERSION=${DISTRIB_ID#"DISTRIB_ID="}
echo "Installing for $VERSION"
case $VERSION in
  Ubuntu) ./ubuntu-setup;;
  Arch | ManjaroLinux)./arch-setup;;
  *) unsupported=true;;
esac

if $unsupported; then
  echo "Distribution unsupported"
  exit 0
fi

cd ../dots
find . -type d -exec sh -xvc 'mkdir -p $HOME/${0#"./"}' {} \;
find . -type f -exec sh -xvc 'ln -srf $0 $HOME/${0#"./"}' {} \;

