#!/bin/bash
set -x

brew install \
  alacritty \
  neovim \
  tmux \
  zsh \
  npm

sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'

cd .../dots || exit
find . -type d -exec sh -xvc 'mkdir -p $HOME/${0#"./"}' {} \;
find . -type f -exec sh -xvc 'rm $HOME/${0#"./"} && ln -snf $(pwd)/$(basename $0) $HOME/${0#"./"}' {} \;

