#!/bin/bash
set -x

unameOut="$(uname -s)"

echo "Detected ${unameOut}"

case "${unameOut}" in
    Linux*) ./linux-setup;;
    Darwin*) ./mac-setup;;
    *) unsupported=true;;
esac

if $unsupported; then
  echo "Device unsupported"
  exit 0
fi

./global-setup

